
name: Build Sigil Plugin Python AppImages

on:
 workflow_dispatch:
  inputs:
  version:
    description: 'Qt version (5|6)'
    required: true

jobs:
  build:
    #if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        wget https://github.com/niess/python-appimage/releases/download/python3.11/python3.11.6-cp311-cp311-manylinux_2_28_x86_64.AppImage
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        ./python3.11.6-cp311-cp311-manylinux_2_28_x86_64.AppImage --appimage-extract
        mv squashfs-root sigil-qt${{ github.event.inputs.version }}-plugin-python3.11.6_x86_64.AppDir
        ln -s sigil-qt${{ github.event.inputs.version }}-plugin-python3.11.6_x86_64.AppDir/AppRun python3.11
        ./python3.11 -m pip install -r requirements${{ github.event.inputs.version }}.txt
        ./appimagetool-x86_64.AppImage -n sigil-qt${{ github.event.inputs.version }}-plugin-python3.11.6_x86_64.AppDir sigil-qt${{ github.event.inputs.version }}-plugin-python3.11.6_x86_64.AppImage

    - name: Upload Artifact
      #if: "contains(github.event.head_commit.message, '[deploy]')"
      uses: actions/upload-artifact@v3
      with:
        name: AppImage-artifact
        path: sigil-qt${{ github.event.inputs.version }}-plugin-python3.11.6_x86_64.AppImage
        retention-days: 3

    #- name: Create Release
    #  if: startswith( github.ref, 'refs/tags/')
    #  uses: ncipollo/release-action@v1
    #  with:
    #    token: ${{ secrets.GITHUB_TOKEN }}
    #    name: ${{ env.PLUGIN_NAME }} ${{ steps.get_tag_name.outputs.TAGNAME }}
    #    body: |
    #      Changes in this Release
    #      - First Change
    #      - Second Change
    #    draft: true
    #    prerelease: false
    #    artifacts: './*.zip'
