
name: Build Sigil Plugin Python AppImages

on:
 workflow_dispatch:
#  inputs:
#    version:
#      description: 'Qt version (5|6)'
#      required: true

jobs:
  build:

    #if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: ['3.11.3']

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '${{matrix.version}}'

    - name: Build Sigil Python AppImage
      run: |
        python3 -m pip install --upgrade pip
        pip3 install python-appimage

    - name: Build Python AppImage
      run: |
        python3 -m python_appimage build local -p /opt/hostedtoolcache/Python/3.*/x64/bin/python3

    - name: Upload Artifact
      #if: "contains(github.event.head_commit.message, '[deploy]')"
      uses: actions/upload-artifact@v3
      with:
        name: AppImage-artifact
        path: *.AppImage
        retention-days: 7

    #- name: Create Release
    #  if: startswith( github.ref, 'refs/tags/')
    #  uses: ncipollo/release-action@v1
    #  with:
    #    token: ${{ secrets.GITHUB_TOKEN }}
    #    name: ${{ env.PLUGIN_NAME }} ${{ steps.get_tag_name.outputs.TAGNAME }}
    #    body: |
    #      Changes in this Release
    #      - First Change
    #      - Second Change
    #    draft: true
    #    prerelease: false
    #    artifacts: './*.zip'
