
name: Build Sigil Plugin Python AppImages

on:
  workflow_dispatch:
#  inputs:
#    version:
#      description: 'Qt version (5|6)'
#      required: true

jobs:
  build:

    #if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: ['3.11.3']

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '${{matrix.version}}'

    - name: Build Sigil Python AppImage
      run: |
        python3 -m pip install --upgrade pip
        pip3 install python-appimage

    - name: Build Python AppImage
      run: |
        echo $(which python3)
        python3 -m python_appimage build local -p /opt/hostedtoolcache/Python/${{matrix.version}}/x64/bin/python3
        ./python3.11.3-x86_64.AppImage --appimage-extract > /dev/null
        mv squashfs-root python3.11.3-x86_64.AppDir
        rm -f ./python3.11.3-x86_64.AppImage
        ln -s  python3.11.3-x86_64.AppDir/AppRun python3.11
        ./python3.11 -m pip install -r requirements6.txt
        rm -rf ./python3.11.3-x86_64.AppDir/opt/python3.11/lib/python3.11/idlelib
        rm -rf ./python3.11.3-x86_64.AppDir/opt/python3.11/lib/python3.11/turtledemo
        rm -rf ./python3.11.3-x86_64.AppDir/opt/python3.11/lib/python3.11/site-packages/python_appimage
        rm -rf ./python3.11.3-x86_64.AppDir/opt/python3.11/lib/python3.11/site-packages/PySide6/Qt
        rm -rf ./python3.11.3-x86_64.AppDir/opt/python3.11/lib/python3.11/site-packages/PySide6/glue
        rm -rf ./python3.11.3-x86_64.AppDir/opt/python3.11/lib/python3.11/site-packages/PySide6/include
        rm -rf ./python3.11.3-x86_64.AppDir/opt/python3.11/lib/python3.11/site-packages/PySide6/scripts
        rm -rf ./python3.11.3-x86_64.AppDir/opt/python3.11/lib/python3.11/site-packages/PySide6/support
        rm -rf ./python3.11.3-x86_64.AppDir/opt/python3.11/lib/python3.11/site-packages/PySide6/typesystems
        rm -rf ./python3.11.3-x86_64.AppDir/opt/python3.11/lib/python3.11/site-packages/*.dist-info
        rm -rf ./python3.11.3-x86_64.AppDir/usr/bin/chardet
        rm -rf ./python3.11.3-x86_64.AppDir/usr/bin/dul*
        rm -rf ./python3.11.3-x86_64.AppDir/usr/bin/pyside6-*
        rm -rf **/__pycache__
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        ./appimagetool-x86_64.AppImage -n python3.11.3-x86_64.AppDir sigil-qt6-python3.11.3-x86_64.AppImage

    - name: Upload Artifact
      #if: "contains(github.event.head_commit.message, '[deploy]')"
      uses: actions/upload-artifact@v3
      with:
        name: AppImage-artifact
        path: sigil-qt6-python3.11.3-x86_64.AppImage
        retention-days: 7

    #- name: Create Release
    #  if: startswith( github.ref, 'refs/tags/')
    #  uses: ncipollo/release-action@v1
    #  with:
    #    token: ${{ secrets.GITHUB_TOKEN }}
    #    name: ${{ env.PLUGIN_NAME }} ${{ steps.get_tag_name.outputs.TAGNAME }}
    #    body: |
    #      Changes in this Release
    #      - First Change
    #      - Second Change
    #    draft: true
    #    prerelease: false
    #    artifacts: './*.zip'
